version: "3"
services: 
    sample-grpc:
        build: . 
        tty: true
        volumes:
            - ./api:/go/src/app
            - ./proto:/proto

    client:
        image: ruby:2.7.1
        tty: true
        volumes:
            - ./client:/client
            - ./proto:/proto